name: Publish examples (presets)
on:
  schedule:
    - cron: "0 16 1/2 * *"
  workflow_dispatch:
  workflow_call:
jobs:
  examples:
    runs-on: ubuntu-latest
    if: "github.repository == 'Shadowghost/gh-metrics'"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - name: Setup metrics
        run: npm ci
      - name: Publish presets examples
        run: npm run presets -- publish
        env:
          GITHUB_TOKEN: ${{ github.token }}


