name: Label issue and pull requests

on: pull_request_target

jobs:
  label:
    name: Label issue and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/config/label.yml
          sync-labels: true
