name: Test (presets)

on:
  pull_request:
    branches: [ presets ]
  workflow_call:
    inputs:
      ref:
        type: string
      repo:
        type: string
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: master
      - name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - name: Setup metrics
        run: npm ci
      - name: Run tests
        run: npm run test-presets
        env:
          HEAD_REF: ${{ inputs.ref }}
          REPO: ${{ inputs.repo }}